version: "3.8"
services:
    db:
        image: postgres:14.1-alpine
        container_name: "${COMPOSE_PROJECT_NAME}_db"
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
        volumes:
            - ./volumes/postgres/data:/var/lib/postgresql/data
        ports:
            - "127.0.0.1:${POSTGRES_EXPOSE_PORT}:5432"
        networks:
            - shopflow_network

    redis:
        image: redis:7.2.4
        container_name: "${COMPOSE_PROJECT_NAME}_redis"
        restart: always
        ports:
            - "127.0.0.1:${REDIS_EXPOSE_PORT}:6379"
        command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
        volumes:
            - ./volumes/redis:/data
        networks:
            - shopflow_network

networks:
    shopflow_network:
        external: true
