name: Deploy Application

on:
  push:
    branches:
      - '*'

jobs:
  create-deployment-artifact:
    name: Create Deployment Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer

      - name: Install PHP Dependencies
        working-directory: ./ShopFlow
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Compile CSS and JavaScript
        working-directory: ./ShopFlow
        run: |
          npm ci
          npm run build

      - name: Setup Environment
        working-directory: ./ShopFlow
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run Pint Test
        working-directory: ./ShopFlow
        run: |
          ./vendor/bin/pint --test

      - name: Run Pest Tests
        working-directory: ./ShopFlow
        run: |
          ./vendor/bin/pest

      - name: Run PHPStan Analysis
        working-directory: ./ShopFlow
        run: |
          ./vendor/bin/phpstan --memory-limit=2048M analyse
